Repository AY2223S1-CS2103T-T15-4/tp, pull requests merged in 2022-10, with the labels that each got.

#61 Regex
  src/main/java/gim/logic/commands/AddCommand.java
  src/main/java/gim/logic/parser/CliSyntax.java
  src/main/java/gim/model/exercise/Rep.java
  src/main/java/gim/model/util/SampleDataUtil.java
  src/main/java/gim/ui/ExerciseCard.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidExerciseAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidExerciseAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateExerciseAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidExerciseAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalExercisesAddressBook.json
  src/test/java/gim/logic/commands/CommandTestUtil.java
  src/test/java/gim/logic/parser/ParserUtilTest.java
  src/test/java/gim/model/exercise/NameContainsKeywordsPredicateTest.java
  src/test/java/gim/model/exercise/RepTest.java
  src/test/java/gim/testutil/EditExerciseDescriptorBuilder.java
  src/test/java/gim/testutil/ExerciseBuilder.java
  src/test/java/gim/testutil/TypicalExercises.java
Labels: priority.High, type.Task

#62 Modify REGEX, constructors and tests to fit new Sets constraints
  src/main/java/gim/logic/parser/CliSyntax.java
  src/main/java/gim/model/exercise/Rep.java
  src/main/java/gim/model/exercise/Sets.java
  src/main/java/gim/model/util/SampleDataUtil.java
  src/test/data/JsonAddressBookStorageTest/invalidExerciseAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateExerciseAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalExercisesAddressBook.json
  src/test/java/gim/logic/commands/CommandTestUtil.java
  src/test/java/gim/logic/parser/ParserUtilTest.java
  src/test/java/gim/model/exercise/NameContainsKeywordsPredicateTest.java
  src/test/java/gim/model/exercise/RepTest.java
  src/test/java/gim/model/exercise/SetsTest.java
  src/test/java/gim/storage/JsonAdaptedExerciseTest.java
  src/test/java/gim/testutil/ExerciseBuilder.java
  src/test/java/gim/testutil/TypicalExercises.java
Labels: priority.High, type.Task

#67 Refactor Rep to Reps for consistency
  src/main/java/gim/logic/commands/AddCommand.java
  src/main/java/gim/logic/commands/EditCommand.java
  src/main/java/gim/logic/parser/AddCommandParser.java
  src/main/java/gim/logic/parser/CliSyntax.java
  src/main/java/gim/logic/parser/EditCommandParser.java
  src/main/java/gim/logic/parser/ParserUtil.java
  src/main/java/gim/model/exercise/Exercise.java
  src/main/java/gim/model/exercise/Reps.java
  src/main/java/gim/model/util/SampleDataUtil.java
  src/main/java/gim/storage/JsonAdaptedExercise.java
  src/main/java/gim/ui/ExerciseCard.java
  src/main/resources/view/ExerciseListCard.fxml
  src/test/data/JsonSerializableExerciseTrackerTest/duplicateExerciseExerciseTracker.json
  src/test/data/JsonSerializableExerciseTrackerTest/invalidExerciseExerciseTracker.json
  src/test/data/JsonSerializableExerciseTrackerTest/typicalExercisesExerciseTracker.json
  src/test/java/gim/logic/LogicManagerTest.java
  src/test/java/gim/logic/commands/CommandTestUtil.java
  src/test/java/gim/logic/commands/EditExerciseDescriptorTest.java
  src/test/java/gim/logic/parser/AddCommandParserTest.java
  src/test/java/gim/logic/parser/EditCommandParserTest.java
  src/test/java/gim/logic/parser/ParserUtilTest.java
  src/test/java/gim/model/ExerciseTrackerTest.java
  src/test/java/gim/model/exercise/ExerciseTest.java
  src/test/java/gim/model/exercise/NameContainsKeywordsPredicateTest.java
  src/test/java/gim/model/exercise/RepsTest.java
  src/test/java/gim/model/exercise/UniqueExerciseListTest.java
  src/test/java/gim/storage/JsonAdaptedExerciseTest.java
  src/test/java/gim/testutil/EditExerciseDescriptorBuilder.java
  src/test/java/gim/testutil/ExerciseBuilder.java
  src/test/java/gim/testutil/ExerciseUtil.java
  src/test/java/gim/testutil/TypicalExercises.java
Labels: priority.Medium, type.Task

#70 Update rep regex
  docs/UserGuide.md
  src/main/java/gim/model/exercise/Reps.java
  src/test/java/gim/model/exercise/RepsTest.java
Labels: priority.Medium, type.Task

#66 Add support for date
  config/checkstyle/checkstyle.xml
  src/main/java/gim/logic/commands/AddCommand.java
  src/main/java/gim/logic/commands/EditCommand.java
  src/main/java/gim/logic/parser/AddCommandParser.java
  src/main/java/gim/logic/parser/CliSyntax.java
  src/main/java/gim/logic/parser/EditCommandParser.java
  src/main/java/gim/logic/parser/ParserUtil.java
  src/main/java/gim/model/date/Date.java
  src/main/java/gim/model/exercise/Exercise.java
  src/main/java/gim/model/tag/Tag.java
  src/main/java/gim/model/util/SampleDataUtil.java
  src/main/java/gim/storage/JsonAdaptedExercise.java
  src/main/java/gim/storage/JsonAdaptedTag.java
  src/main/java/gim/ui/ExerciseCard.java
  src/main/resources/view/ExerciseListCard.fxml
  src/test/data/JsonExerciseTrackerStorageTest/invalidAndValidExerciseExerciseTracker.json
  src/test/data/JsonExerciseTrackerStorageTest/invalidExerciseExerciseTracker.json
  src/test/data/JsonSerializableExerciseTrackerTest/duplicateExerciseExerciseTracker.json
  src/test/data/JsonSerializableExerciseTrackerTest/invalidExerciseExerciseTracker.json
  src/test/data/JsonSerializableExerciseTrackerTest/typicalExercisesExerciseTracker.json
  src/test/java/gim/logic/LogicManagerTest.java
  src/test/java/gim/logic/commands/CommandTestUtil.java
  src/test/java/gim/logic/commands/EditCommandTest.java
  src/test/java/gim/logic/commands/EditExerciseDescriptorTest.java
  src/test/java/gim/logic/parser/AddCommandParserTest.java
  src/test/java/gim/logic/parser/EditCommandParserTest.java
  src/test/java/gim/logic/parser/ParserUtilTest.java
  src/test/java/gim/model/ExerciseTrackerTest.java
  src/test/java/gim/model/date/DateTest.java
  src/test/java/gim/model/exercise/ExerciseTest.java
  src/test/java/gim/model/exercise/UniqueExerciseListTest.java
  src/test/java/gim/storage/JsonAdaptedExerciseTest.java
  src/test/java/gim/testutil/EditExerciseDescriptorBuilder.java
  src/test/java/gim/testutil/ExerciseBuilder.java
  src/test/java/gim/testutil/ExerciseUtil.java
  src/test/java/gim/testutil/TypicalExercises.java
Labels: priority.High, type.Task

#74 Improve display message shown
  src/main/java/gim/model/exercise/Exercise.java
Labels: priority.Low

#84 UI update
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
  src/main/java/gim/ui/HelpWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement

#101 Update DeveloperGuide to include SortCommand
  docs/DeveloperGuide.md
  docs/diagrams/SortSequenceDiagram.puml
  docs/images/SortSequenceDiagram.png
Labels: documentation, priority.Medium

#102 [Update DG] Listing Exercise Keys in graphical UI
  docs/DeveloperGuide.md
  docs/diagrams/ObserverPattern.puml
  docs/diagrams/style.puml
  docs/images/ObserverPattern.png
Labels: documentation, priority.Medium

#108 Allow empty date field for add command and additional enhancements
  src/main/java/gim/logic/parser/AddCommandParser.java
  src/main/java/gim/logic/parser/ParserUtil.java
  src/main/java/gim/model/date/Date.java
  src/main/java/gim/storage/JsonAdaptedDate.java
  src/main/java/gim/storage/JsonAdaptedExercise.java
  src/main/java/gim/storage/JsonAdaptedTag.java
  src/test/java/gim/model/date/DateTest.java
  src/test/java/gim/storage/JsonAdaptedExerciseTest.java
Labels: enhancement, priority.Medium

#111 Change the colour of application displayed
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
Labels: priority.Low

#107 Exercise keys logic
  src/main/java/gim/logic/Logic.java
  src/main/java/gim/logic/LogicManager.java
  src/main/java/gim/logic/commands/ClearCommand.java
  src/main/java/gim/model/ExerciseTracker.java
  src/main/java/gim/model/Model.java
  src/main/java/gim/model/ModelManager.java
  src/main/java/gim/model/exercise/ExerciseHashMap.java
  src/main/java/gim/model/exercise/ExerciseKeys.java
  src/main/java/gim/ui/MainWindow.java
  src/main/java/gim/ui/Observer.java
  src/main/java/gim/ui/SavedExerciseListWindow.java
  src/test/java/gim/logic/commands/AddCommandTest.java
  src/test/java/gim/model/exercise/ExerciseHashMapTest.java
  src/test/java/gim/model/exercise/ExerciseKeysTest.java
Labels: priority.High, type.Story

#100 Implement new Sort Command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/gim/MainApp.java
  src/main/java/gim/logic/commands/ExitCommand.java
  src/main/java/gim/logic/commands/FindCommand.java
  src/main/java/gim/logic/commands/SortCommand.java
  src/main/java/gim/logic/parser/ExerciseTrackerParser.java
  src/main/java/gim/model/ExerciseTracker.java
  src/main/java/gim/model/Model.java
  src/main/java/gim/model/ModelManager.java
  src/main/java/gim/model/exercise/Exercise.java
  src/main/java/gim/model/exercise/ExerciseList.java
  src/test/java/gim/logic/commands/AddCommandTest.java
  src/test/java/gim/logic/commands/EditCommandTest.java
  src/test/java/gim/logic/commands/FindCommandTest.java
  src/test/java/gim/logic/commands/SortCommandTest.java
  src/test/java/gim/model/ExerciseTrackerTest.java
  src/test/java/gim/model/exercise/ExerciseListTest.java
  src/test/java/gim/testutil/TypicalExercises.java
Labels: priority.High, type.Story

#115 Help Window UI update
  docs/UserGuide.md
  src/main/java/gim/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: priority.Medium, type.Enhancement

#119 Implement range command and enhancements
  docs/UserGuide.md
  docs/images/RangeCommandOneSample.png
  docs/images/RangeCommandTwoSample.png
  src/main/java/gim/commons/core/Messages.java
  src/main/java/gim/logic/commands/RangeCommand.java
  src/main/java/gim/logic/parser/AddCommandParser.java
  src/main/java/gim/logic/parser/CliSyntax.java
  src/main/java/gim/logic/parser/ExerciseTrackerParser.java
  src/main/java/gim/logic/parser/ParserUtil.java
  src/main/java/gim/logic/parser/RangeCommandParser.java
  src/main/java/gim/model/date/Date.java
  src/main/java/gim/model/date/FormatterList.java
  src/main/java/gim/model/date/RegexList.java
  src/main/java/gim/model/exercise/DateWithinRangePredicate.java
  src/main/java/gim/model/exercise/ExerciseList.java
  src/main/java/gim/storage/JsonAdaptedDate.java
  src/main/java/gim/storage/JsonAdaptedExercise.java
  src/main/java/gim/ui/ExerciseCard.java
  src/test/java/gim/logic/commands/CommandTestUtil.java
  src/test/java/gim/logic/commands/RangeCommandTest.java
  src/test/java/gim/logic/parser/AddCommandParserTest.java
  src/test/java/gim/logic/parser/EditCommandParserTest.java
  src/test/java/gim/logic/parser/RangeCommandParserTest.java
  src/test/java/gim/model/date/DateTest.java
  src/test/java/gim/model/date/FormatterListTest.java
  src/test/java/gim/model/date/RegexListTest.java
  src/test/java/gim/model/exercise/DateWithinRangePredicateTest.java
Labels: enhancement, priority.High

#113 Add welcome message when application is launched
  src/main/java/gim/logic/commands/AddCommand.java
  src/main/java/gim/logic/commands/DeleteCommand.java
  src/main/java/gim/logic/commands/EditCommand.java
  src/main/java/gim/logic/commands/FindCommand.java
  src/main/java/gim/logic/commands/GenerateCommand.java
  src/main/java/gim/logic/commands/HelpCommand.java
  src/main/java/gim/logic/commands/PrCommand.java
  src/main/java/gim/logic/commands/RangeCommand.java
  src/main/java/gim/ui/MainWindow.java
  src/main/java/gim/ui/ResultDisplay.java
Labels: priority.Low

#126 Update User guide
  README.md
  docs/UserGuide.md
  docs/images/GUIOrientation.png
  docs/images/RecognisedExercisesOrientation.PNG
  docs/images/Ui.png
Labels: documentation, priority.Medium, type.Task

#128 Improve range command
  docs/UserGuide.md
  docs/images/RangeCommandOneSample.png
  docs/images/RangeCommandTwoSample.png
  src/main/java/gim/logic/commands/RangeCommand.java
  src/main/java/gim/logic/parser/CliSyntax.java
  src/main/java/gim/logic/parser/RangeCommandParser.java
  src/main/java/gim/model/date/Date.java
  src/main/java/gim/model/date/RegexList.java
  src/test/java/gim/logic/commands/CommandTestUtil.java
Labels: priority.High, type.Enhancement

#130 Update UG for accepted date formats
  docs/UserGuide.md
Labels: documentation

#134 update UG
  docs/UserGuide.md
  docs/images/GUIOrientation.png
  docs/images/RecognisedExercisesOrientation.png
Labels: priority.Low, type.Task

#189 UG update
  docs/UserGuide.md
  docs/images/AddCommand.png
  docs/images/FilterCommand.png
  docs/images/GUIOrientation.png
  docs/images/GenerateCommandExample1.png
  docs/images/GenerateCommandExample2.png
  docs/images/GenerateCommandNameExample1.png
  docs/images/ListAfterSortCommand.png
  docs/images/PrCommandExample1.png
  docs/images/PrCommandExample2.png
  docs/images/RangeCommandOneSample.png
  docs/images/RangeCommandTwoSample.png
  docs/images/RecognisedExercisesOrientation.png
Labels: documentation, priority.Medium
